@startuml

package CoreData {

    interface Core<S> {
        +process(service, request, callback)

        +loadActivity(activity)
        +unloadActivity(activity)

        +loadService(service)
        +unloadService(service)
    }

    interface GraphicsContext<N> {
        +bind(rootNode)
        +unbind(rootNode)
    }

    interface ApplicationContext {
        +getDocumentsDAO(): DataAccessObject<Document>
        +getUsersDAO(): DataAccessObject<User>
    }

    interface Activity<N> {
        +onLoad(graphicContext)
        +onUnload(graphicContext)
    }

    interface Service<A, R> {
        +onLoad(core)
        +onUnload(core)
    }

    interface PureService<A, R> {
        +process(request, callback)
    }

    interface DataService<A, R> {
        +process(request, callback, dataContext)
    }

}

package Utils {

    package Data {

        class DataAccessObject<S> {
            +beginTransaction(): Transaction<S>
        }

        class Transaction<S> {
            +getAll(): Stream<S>
            +save(S object): void
            +update(S object): void
            +delete(S object): void
        }

    }
}

package Model {

    class Document {

    }

    class User {

    }

}

Core --> Activity
Core --> Service
Activity --> GraphicsContext
Service --> ApplicationContext
ApplicationContext --> DataAccessObject
ApplicationContext --> User
ApplicationContext --> Document
DataAccessObject --> Transaction

@enduml