@startuml
left to right direction

Пользователь  <|- Автор

Пользователь -- (Получить ревизию)
(Получить ревизию) -- Cистема

Пользователь -- (Комментрировать ревизию)
(Комментрировать ревизию) -- Cистема
(Комментрировать ревизию) <. (Получить ревизию) : <<extends>>

Автор -- (Создать ревизию)
(Создать ревизию) -- Cистема

Автор -- (Создать документ)
(Создать документ) -- Cистема
(Создать ревизию) .> (Создать документ) : <<include>>


@enduml